a=[
"ADRIANA NATASYA YONG BINTI MOHD FAREEZ",
"AHMAD IBRAHIM MUBIN",
"MUHAMMAD MIKAEL ZIDANE BIN MOHD KHAIRUL SHAH",
"AHMAD MUAZ BIN AHMAD HAMBALI",
"MARYAM ALISHA BINTI AHMAD NAZER",
"MUHAMMAD AQLAN ALIYAN BIN MUHAMMAD SUKRI",
"AMR ADAM UMARISYH BIN AMRUL AMIN",
"IMAN RIZQI BIN ISAHRUDIN",
"SHAHRUL ARIFF IDZHAM BIN MUHAMMAD SAIFUL HADI",
"SHAFA KHALILI BINTI AHMAD SHAHIR",
"MUHAMMAD THORIQ",
"MUHAMMAD ZIYAD RIZQI BIN MOHD RAZI",
"EUSOFF BIN MOHD NURUL ANWAR",
"MUHAMMAD AQEEF DANIEL BIN MOHD ASHAARI",
"MOHAMAD AMZAR BIN SYARYFUDEEN",
"FADHLAN BIN MUHAMMAD NAJIB",
"MUHAMMAD ILHAM RIZQI",
"AMR YOUSSEF HAKIMIE",
"Muhammad farrell iskander",
"Ahmad Baihaqi bin Mohd Hariz",
"Eulorra Phatima Binti Saiful Zahari",
"Nuur Faiqah Faqihah Binti Hairolnijam",
"Nur Aisyah Khaira",
"NUR ALISHA FARHANA",
"Muhammad aiqil hairi",
"MUHAMMAD HARIZ FARHAN BIN MOHD FARIZ",
"Muhammad arieq zayyan bin mohd zamri",
"MUHAMMAD HADIF BIN ABDUL HALIM",
"Nur Damia Aqeela",
"MUHAMMAD SHAZRAY REYQAL BIN SAIFUL ADLI",
"Qaleesh U’qael bin Muhamad Amirul",
"Nur Adreen Firdaani bt Farid",
"NUR ADRIANA QAIRINA BT SHAMSHUL",
"ZAYD",
"Noah Hakeem bin Muhammad Safwan",
"Raja Nurul Kauthar binti Raja Mohd Khalid",
"NUUR AUFA HANA BINTI MOHD HANIF",
"Muhammad Syazwan bin Suhaiimran",
"MUHAMMAD MIKHAIL ZAFRAN BIN AZFIZULRIZAL",
"Nik Muhammad Anas bin Nik Sahazeman",
"Akif Arif Bin Mohamad Adli",
"muhammad fateh khalish bin abdul rasid",
"Muhammad Aqeef Fauzan Bin Noor Azam",
"Sharul Shakir bin Sharul Rozain",
"MUHAMMAD SYAHMI NAQEEB",
"Mohamad harith sufyan",
"MUHAMMAD IZUWAN BIN MOHD AZRIN",
"AHMAD DANI IZZAN BIN MOHD SUFIAN",
"NUH KHALEEF MIRZA BIN AZHAREZZA",
"Harris Rafael b. Mohd Hazrul",
"Wan Naurah Aysha",
"IMAN ALFATEH BIN MOHD SHAIFUL BAKRI",
"Aryash khaasif bin faizul",
"Muhammad Fateh Hadif bin Mohamad Aminuddin",
"Muhammad Izz Aryaan Affandi bin Mohd Shahril Affandi",
"Amsyar Zafran bin Khairul Azhar",
"Aqil al zarif",
"Muhammad Aqeeb Zayyan",
"Safran Helmy bin Mohd Shahrul Amin",
"Muhammad Hadiy Aisy",
"Rayyan Hakimi Bin Nicko Yuda Putra",
"Muhammad Aryan",
"Harraz Rayhan bin Husaini",
"Muhammad Al Fateh",
"Fattaah Widad Bin Arzlan",
"Muhammad Yusuf bin Maidin",
"Muhammad amir khalif bin muhd nur akmal",
"Muhamad Qoid Iskandar Bin Muhamad Faizul",
"Fara maleeqa aurora bt ramizan",
"ALI IMRAN BIN AZMI",
"NUR IRDINA IZZATI BINTI MOHD ROSLY",
"Dhia Callista Chong",
"Amira Naira Sumayyah Binti Hafiz",
"Muhammad Thaqif Raihan bin Muhammad Shah Redza",
"MUHAMMAD HARRAZ FARHAN BIN ABDUL MUTALIB",
"Muhammad Adam Kamil",
"MUHAMMAD RAYYAN AZFAR BIN MAZLAN",
"NUR MARISSA ALEEYA BINTI MAZLAN",
"AMMAR DZULFAHMI",
"Muhammad Dayyaan Nubayl",
"EIMAN YUSUF BIN MOHD FAIRUZ",
"Aisyah binti Ahmad Faizal",
"Ahmad ammar fayyadh bin mohd fauzan",
"fathiah husna binti ahmad tajuddin",
"Fareen Laiqa bt Fadhli",
"Nurin Jazmina binti Muhammad Hasrun",
"yeow khai yip",
"muhammad firas mikail bin muhammad faizal",
"Mar'ie bin marzuki",
"Muhammad Aryan",
"FARHATUN ELMIERA",
"MOHAMMAD ADAM ARYAN BIN IMAM KHARMAIN",
"ayman arsyad bin saiful bahri",
"LUTH NOR BIN ZAKARIA NOR",
"IMAN NUR ARIANA BINTI MUHAMMAD KHAIRUL EKHSAN",
"Noah bin Mohd Khairul Affan",
"ahmad fardain adrish",
"Nor Ammar Iskandar bin Norzafrin",
"Faris aiman bin faryzan",
"Adli hazmi bin abu hassan",
"Nur Inarah Binti Muhammad Umar",
"HUD BIN MUHAMAD FAZRI",
"Dayyan haiyan bin mohd afham",
"Dayyan Aryan bin Mohd Afham",
"Sayf Aydeen bin Mohamad Shaheer",
"Tuan Ahmad Zharif Bin Tuan Mohamad Ezat",
"AHMAD AFIQ BIN ARSHAD",
"Nawfal Muizzuddin Bin Musa",
"AQEEL HARIZ BIN NOR AZWAN",
"Iyaad ilham b. Hairazi",
"Daniel bin Muhammad Faiz",
"AHMAD RAYYAN MIKHAEL BIN AHMAD HIDAYAT",
"airisya nurisya",
"AISY NUR HUMAIRA BINTI ABDUL RAHMAN",
"Ali Al-Mohsi",
"Ashraff Fahmi bin Fazli",
"Izz Hana Amanda",
"LUQMAN HAZIQ",
"Muhammad Adam Faliqh Uqasha",
"Muhammad Adam Harith",
"MUHAMMAD AQLAN MUTTAQIN BIN MOHAMAD RIZUWAN",
"Muhammad faeq syameel bin mohd faizal",
"MUHAMMAD SAFWAN BIN MOHD SHAHRIL",
"MUHAMMAD SYAZWAN BIN MOHD SHAHRIL",
"NASUHA QAISARA",
"Nur Amani Nabihah binti Mohammad Zaki",
"SAYF AMNAAN BIN AMIRUL ASRAF",
"SITI HANNAH SAFIYYAH BINTI HAFIZ",
"ASYRAAF FARIS",
"KHAIRUL ZIKRI ",
"MUHAMMAD AL BAIHAQI",
"MUHAMMAD IMRAN",
"ahla binti mohd faisal",
"Muhammad Nur Iman Zuhair",
"NUR SAKIENAH SAMSUDIN",
"Mohammad Rusyaidi Azri Bin Zulkeffli",
"SOFIA AKIFA NAYLA BINTI MOHD HASRIL",
"Muhammad Eiman Rizqullah bin Mohd Redzuan",
"Nur Areessa Summayyah Muhammad Hafiz",
"Che Salma Aleesya Mujahidah binti Che Mohammad Fadhli",
"Che Nur Hannah Mujahidah binti Che Mohammad Fadhli",
"AHMAD 'ARIFF BIN MOHD SAIFUDDIN",
"IMAN ZHARIF BIN ABDUL HALFIZ",
"Hor Kah Lok",
"Muhammad Al Fatih",
"Areez Aaryanz bin Mohd Salmy",
"SHARIFAH SOFIA ZAHRAA",
"Nur An-nisa’ Faiqa",
"zarif haikal bin zahreen",
"MUHAMMAD FAREESH MUHAMMAD FAHMY",
"muhammad umar",
"Qalif Muhammad Bin Mohamad Rais",
"Nur Aina Zara binti Shahrul Hairri",
"Muhammad Adam Shafwan bin Shahrul Hairri",
"NUR AIRA DARWISYA"]

b=[]
Ekid.where(name: a).each do |ek|
b << ek.name
end

b.each do |ek|
puts ek
end



